/*
Script generated by Aqua Data Studio 18.5.0-4 on abr-13-2018 08:13:02 PM
Database: orclpdb1
Schema: COMTECSIS
Objects: TABLE
*/

-- <Para crear usuario>
-- CREATE USER comtecsis IDENTIFIED BY comtecsis;
-- GRANT CONNECT TO comtecsis;
-- GRANT CONNECT, RESOURCE, DBA TO comtecsis;
-- GRANT UNLIMITED TABLESPACE TO comtecsis;
-- </Para crear usuario>

-- <Para regenerar tablas>
-- DROP TABLE "COMTECSIS"."translate"
-- GO
-- DROP TABLE "COMTECSIS"."appconfiguration"
-- GO
-- </Para regenerar tablas>

CREATE TABLE "COMTECSIS".appconfiguration  ( 
  propertykey   VARCHAR2(30 BYTE) NOT NULL,
  propertyvalue VARCHAR2(200 BYTE) NOT NULL,
  CONSTRAINT propertykey PRIMARY KEY(propertykey)
  NOT DEFERRABLE VALIDATE 
)
GO
CREATE TABLE "COMTECSIS".translate  ( 
  code  VARCHAR2(30 BYTE) NOT NULL,
  en    VARCHAR2(600 BYTE) NOT NULL,
  es    VARCHAR2(600 BYTE) NOT NULL,
  CONSTRAINT code PRIMARY KEY(code)
  NOT DEFERRABLE VALIDATE 
)
GO

INSERT INTO "COMTECSIS".appconfiguration(propertykey, propertyvalue)
  VALUES('delay.ajax', '3000')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('home-ubigeo-link', 'Ubications', 'Ubicaciones')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('txt-departament', 'Departament', 'Departamento')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('txt-province', 'Province', 'Provincia')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('txt-district', 'District', 'Distrito')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('txt-description', 'Description', 'Descripción')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('txt-actions', 'Actions', 'Acciones')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('txt-add', 'Add', 'Agregar')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('txt-edit', 'Edit', 'Editar')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('txt-drop', 'Delete', 'Eliminar')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('txt-save', 'Save', 'Guardar')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('ubigeo-list-find-placeholder', 'Name of department, province or district.', 'Nombre de departamento, provincia o distrito.')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('txt-code', 'Code', 'Codigo')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('txt-find', 'Find', 'Buscar')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('ubigeo-create-title', 'Register of Ubigeo', 'Registro de ubigeo')
GO
INSERT INTO "COMTECSIS".translate(code, en, es)
  VALUES('txt-go-back', 'Go Back', 'Atrás')
GO
